name: Powershell
on: [push, pull_request]

jobs:

  test:
    name: Multiple
    
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: create
        run: .\c.ps1
        shell: powershell
